# Generated by Django 6.0.6 on 2026-06-25 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(blank=True, max_length=25, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('anonymous', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Theft', 'Theft'), ('Assault', 'Assault'), ('Cyber Crime', 'Cyber Crime'), ('Domestic Violence', 'Domestic Violence'), ('Missing Person', 'Missing Person'), ('Drug Crime', 'Drug Crime'), ('Traffic Violation', 'Traffic Violation'), ('Fraud', 'Fraud'), ('Robbery', 'Robbery'), ('Other', 'Other')], default='Other', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('crime_date', models.DateField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Investigating', 'Investigating'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('fir_generated', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='crime_compl_status_fe46da_idx'), models.Index(fields=['category'], name='crime_compl_categor_c0a5c2_idx'), models.Index(fields=['priority'], name='crime_compl_priorit_6f43a2_idx'), models.Index(fields=['created_at'], name='crime_compl_created_f5df0e_idx')],
            },
        ),
    ]
